name: "Dynamic matrix"

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'build strategy'
        required: true
        type: choice
        default: all
        options:
        - all
        - big-merge
        - pgo

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/generate-matrix
      id: set-matrix
      with:
        strategy: ${{ inputs.strategy }}

  build-on-copr:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.mymatrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name=${{ matrix.name }}"
