name: "Dynamic matrix"

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'build strategy'
        required: true
        type: choice
        options:
        - big-merge
        - pgo

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.set-matrix.outputs.myoutput }}
    steps:
    - id: set-matrix
      run: |
        BIG_MERGE_CONFIG=$(jq -c <<EOF
          {
              "name": "big-merge",
              "copr_project_tpl": "@fedora-llvm-team/llvm-snapshots-big-merge-YYYYMMDD",
              "copr_target_project": "@fedora-llvm-team/llvm-snapshots",
              "clone_url_tpl": "https://src.fedoraproject.org/rpms/PKG.git",
              "clone_ref": "rawhide"
          }
        EOF
        )

        PGO_CONFIG=$(jq -c <<EOF
          {
            "name": "pgo",
            "copr_project_tpl": "@fedora-llvm-team/llvm-snapshots-pgo-YYYYMMDD",
            "copr_target_project": "@fedora-llvm-team/llvm-snapshots-pgo",
            "extra_script_file": "scripts/functions-pgo.sh",
            "clone_url_tpl": "https://src.fedoraproject.org/forks/kkleine/rpms/PKG.git",
            "clone_ref": "pgo"
          }
        EOF
        )

        if [[ '${{ inputs.strategy }}' == 'big-merge' ]]; then
          INCLUDES="[$BIG_MERGE_CONFIG]"
        elif [[ '${{ inputs.strategy }}' == 'pgo' ]]; then
          INCLUDES="[$PGO_CONFIG]"
        else
          INCLUDES="[$BIG_MERGE_CONFIG, $PGO_CONFIG]"
        fi
        echo "myoutput=$(jq -cn --argjson includes "$INCLUDES" '{include:$includes}')" >> $GITHUB_OUTPUT

  build-on-copr:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.mymatrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name=${{ matrix.name }}"
