name: "Dynamic matrix"

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'build strategy'
        required: true
        type: choice
        options:
        - big-merge
        - pgo

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.set-matrix.outputs.myoutput }}
    steps:
    - id: set-matrix
      run: |
        NAMES='["big-merge"]'

        BIG_MERGE_CONFIG=$(jq -c <<EOF
          {
              "name": "big-merge",
              "copr_project_tpl": "@fedora-llvm-team/llvm-snapshots-big-merge-YYYYMMDD",
              "copr_target_project": "@fedora-llvm-team/llvm-snapshots",
              "clone_url_tpl": "https://src.fedoraproject.org/rpms/PKG.git",
              "clone_ref": "rawhide"
          }
        EOF
        )

        PGO_CONFIG=$(jq -c <<EOF
          {
            "name": "pgo",
            "copr_project_tpl": "@fedora-llvm-team/llvm-snapshots-pgo-YYYYMMDD",
            "copr_target_project": "@fedora-llvm-team/llvm-snapshots-pgo",
            "extra_script_file": "scripts/functions-pgo.sh",
            "clone_url_tpl": "https://src.fedoraproject.org/forks/kkleine/rpms/PKG.git",
            "clone_ref": "pgo"
          }
        EOF
        )

        if [[ ${{ github.event_name != 'workflow_dispatch' }} ]]; then
          NAMES='["big-merge", "pgo"]'
          INCLUDES="[$BIG_MERGE_CONFIG, $PGO_CONFIG]"
        elif [[ ${{ inputs.strategy }} == 'big-merge' ]]; then
          NAMES='["${{ inputs.strategy }}"]'
          INCLUDES="[$BIG_MERGE_CONFIG]"
        elif [[ ${{ inputs.strategy }} == 'pgo' ]]; then
          NAMES='["${{ inputs.strategy }}"]'
          INCLUDES="[$PGO_CONFIG]"
        fi
        echo "myoutput=$(jq -cn --argjson names "$NAMES" --argjson includes "$INCLUDES" '{name: $names, include:$includes}')" >> $GITHUB_OUTPUT

  build-on-copr:
    needs: job1
    strategy:      
      fail-fast: false
      matrix: ${{fromJson(needs.job1.outputs.mymatrix)}}
        # include:
        #   - name: big-merge
        #     copr_project_tpl: "@fedora-llvm-team/llvm-snapshots-big-merge-YYYYMMDD"
        #     copr_target_project: "@fedora-llvm-team/llvm-snapshots"
        #     clone_url_tpl: "https://src.fedoraproject.org/rpms/PKG.git"
        #     clone_ref: rawhide
        #   - name: pgo
        #     copr_project_tpl: "@fedora-llvm-team/llvm-snapshots-pgo-YYYYMMDD"
        #     copr_target_project: "@fedora-llvm-team/llvm-snapshots-pgo"
        #     extra_script_file: "scripts/functions-pgo.sh"
        #     clone_url_tpl: "https://src.fedoraproject.org/forks/kkleine/rpms/PKG.git"
        #     clone_ref: pgo
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name=${{ matrix.name }}"
          echo "clone_ref=${{ matrix.clone_ref }}"
