name: build
on: 
  workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set +e          
          echo "tmp_exists=`test -e /tmp && 1 || 0`" >> $GITHUB_ENV
          echo "foo_exists=`test -e /foo && 1 || 0`" >> $GITHUB_ENV
          set -e
          
      - if: ${{ env.tmp_exists }} == "yes"
        env:
          tmp_exists: ${{env.tmp_exists}}
        run: |
          echo "/tmp exists"
    
      - if: ${{ env.foo_exists }} == "yes"
        env:
          foo_exists: ${{env.foo_exists}}
        run: |
          echo "/foo exists"
